<?php
// Register Custom Post Type
$post_types = [
	'zimmer' => [
		'label'                 => __( 'Zimmer', 'white-zimmer' ),
		'labels'                => [
			'name'                  => _x( 'Zimmers', 'Post Type General Name', 'white-zimmer' ),
			'singular_name'         => _x( 'Zimmer', 'Post Type Singular Name', 'white-zimmer' ),
			'menu_name'             => __( 'Zimmers', 'white-zimmer' ),
			'name_admin_bar'        => __( 'Zimmers', 'white-zimmer' ),
			'archives'              => __( 'Zimmer Archives', 'white-zimmer' ),
			'attributes'            => __( 'Zimmer Attributes', 'white-zimmer' ),
			'all_items'             => __( 'All Zimmers', 'white-zimmer' ),
			'add_new_item'          => __( 'Add New Zimmer', 'white-zimmer' ),
			'new_item'              => __( 'New Zimmer', 'white-zimmer' ),
			'edit_item'             => __( 'Edit Zimmer', 'white-zimmer' ),
			'update_item'           => __( 'Update Zimmer', 'white-zimmer' ),
			'view_item'             => __( 'View Zimmer', 'white-zimmer' ),
			'view_items'            => __( 'View Zimmers', 'white-zimmer' ),
			'search_items'          => __( 'Search Zimmers', 'white-zimmer' ),
			'insert_into_item'      => __( 'Insert into Zimmer', 'white-zimmer' ),
			'uploaded_to_this_item' => __( 'Uploaded to this Zimmer', 'white-zimmer' ),
			'items_list'            => __( 'Zimmers list', 'white-zimmer' ),
			'items_list_navigation' => __( 'Zimmers list navigation', 'white-zimmer' ),
			'filter_items_list'     => __( 'Filter Zimmers list', 'white-zimmer' ),
		],
		'supports'              => array( 'title', 'editor', 'thumbnail' ),
		'taxonomies'            => array( 'areas', 'zimmer_features' ),
		'hierarchical'          => false,
		'public'                => true,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 5,
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => true,
		'exclude_from_search'   => false,
		'publicly_queryable'    => true,
		'capability_type'       => 'page',
	],

	'review' => [
		'label'                 => __( 'Review', 'white-zimmer' ),
		'labels'                => [
			'name'                  => _x( 'Reviews', 'Post Type General Name', 'white-zimmer' ),
			'singular_name'         => _x( 'Review', 'Post Type Singular Name', 'white-zimmer' ),
			'menu_name'             => __( 'Reviews', 'white-zimmer' ),
			'name_admin_bar'        => __( 'Reviews', 'white-zimmer' ),
			'archives'              => __( 'Review Archives', 'white-zimmer' ),
			'attributes'            => __( 'Review Attributes', 'white-zimmer' ),
			'all_items'             => __( 'All Reviews', 'white-zimmer' ),
			'add_new_item'          => __( 'Add New Review', 'white-zimmer' ),
			'new_item'              => __( 'New Review', 'white-zimmer' ),
			'edit_item'             => __( 'Edit Review', 'white-zimmer' ),
			'update_item'           => __( 'Update Review', 'white-zimmer' ),
			'view_item'             => __( 'View Review', 'white-zimmer' ),
			'view_items'            => __( 'View Reviews', 'white-zimmer' ),
			'search_items'          => __( 'Search Reviews', 'white-zimmer' ),
			'insert_into_item'      => __( 'Insert into Review', 'white-zimmer' ),
			'uploaded_to_this_item' => __( 'Uploaded to this Review', 'white-zimmer' ),
			'items_list'            => __( 'Reviews list', 'white-zimmer' ),
			'items_list_navigation' => __( 'Reviews list navigation', 'white-zimmer' ),
			'filter_items_list'     => __( 'Filter Reviews list', 'white-zimmer' ),
		],
		'supports'              => array( 'title', 'editor', 'custom-fields' ),
		'hierarchical'          => false,
		'public'                => false,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 5,
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => false,
		'exclude_from_search'   => true,
		'publicly_queryable'    => true,
		'capability_type'       => 'post',
	],
];
