<?php

$taxonomies = [
	'areas' => [
		'labels' => [
			'name'                       => _x( 'Areas', 'Taxonomy General Name', 'white-zimmer' ),
			'singular_name'              => _x( 'Area', 'Taxonomy Singular Name', 'white-zimmer' ),
			'menu_name'                  => __( 'Areas', 'white-zimmer' ),
			'all_items'                  => __( 'All Areas', 'white-zimmer' ),
			'parent_item'                => __( 'Parent Area', 'white-zimmer' ),
			'parent_item_colon'          => __( 'Parent Area:', 'white-zimmer' ),
			'new_item_name'              => __( 'New Area Name', 'white-zimmer' ),
			'add_new_item'               => __( 'Add New Area', 'white-zimmer' ),
			'edit_item'                  => __( 'Edit Area', 'white-zimmer' ),
			'update_item'                => __( 'Update Area', 'white-zimmer' ),
			'view_item'                  => __( 'View Area', 'white-zimmer' ),
			'separate_items_with_commas' => __( 'Separate areas with commas', 'white-zimmer' ),
			'add_or_remove_items'        => __( 'Add or remove areas', 'white-zimmer' ),
			'choose_from_most_used'      => __( 'Choose from the most used', 'white-zimmer' ),
			'popular_items'              => __( 'Popular Areas', 'white-zimmer' ),
			'search_items'               => __( 'Search Areas', 'white-zimmer' ),
			'not_found'                  => __( 'Not Found', 'white-zimmer' ),
			'no_terms'                   => __( 'No areas', 'white-zimmer' ),
			'items_list'                 => __( 'Areas list', 'white-zimmer' ),
			'items_list_navigation'      => __( 'Areas list navigation', 'white-zimmer' ),
		],
		'hierarchical' => true,
		'public' => true,
		'show_ui' => true,
		'show_admin_column' => true,
		'show_in_nav_menus' => true,
		'show_tagcloud' => true,
	],

	'zimmer_features' => [
		'labels' => [
			'name'                       => _x( 'Features', 'Taxonomy General Name', 'white-zimmer' ),
			'singular_name'              => _x( 'Feature', 'Taxonomy Singular Name', 'white-zimmer' ),
			'menu_name'                  => __( 'Features', 'white-zimmer' ),
			'all_items'                  => __( 'All Features', 'white-zimmer' ),
			'parent_item'                => __( 'Parent Feature', 'white-zimmer' ),
			'parent_item_colon'          => __( 'Parent Feature:', 'white-zimmer' ),
			'new_item_name'              => __( 'New Feature Name', 'white-zimmer' ),
			'add_new_item'               => __( 'Add New Feature', 'white-zimmer' ),
			'edit_item'                  => __( 'Edit Feature', 'white-zimmer' ),
			'update_item'                => __( 'Update Feature', 'white-zimmer' ),
			'view_item'                  => __( 'View Feature', 'white-zimmer' ),
			'separate_items_with_commas' => __( 'Separate areas with commas', 'white-zimmer' ),
			'add_or_remove_items'        => __( 'Add or remove areas', 'white-zimmer' ),
			'choose_from_most_used'      => __( 'Choose from the most used', 'white-zimmer' ),
			'popular_items'              => __( 'Popular Features', 'white-zimmer' ),
			'search_items'               => __( 'Search Features', 'white-zimmer' ),
			'not_found'                  => __( 'Not Found', 'white-zimmer' ),
			'no_terms'                   => __( 'No areas', 'white-zimmer' ),
			'items_list'                 => __( 'Features list', 'white-zimmer' ),
			'items_list_navigation'      => __( 'Features list navigation', 'white-zimmer' ),
		],
		'hierarchical' => true,
		'public' => true,
		'show_ui' => true,
		'show_admin_column' => true,
		'show_in_nav_menus' => true,
		'show_tagcloud' => true,
	],
];
